[package]
name = "ws_code"
version = "0.1.0"
edition = "2021"

[dependencies]
warp ="0.3.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.8"
futures = "0.3.17"
log = "0.4.17"
pretty_env_logger = "0.5.0"